### ISSUE TITLE
Not upgrading?

### ISSUE THREAD

**Issue by mabahj** [maaximal/jottadocker#1]
Hi,
I'm trying out your very nice package. Thank you.

I am, however, not able to get it to upgrade to the latest package. The installation starts with jotta-cli 0.7.33634 and it stays there. The console says "jotta-cli is already the newest version (0.7.33634)." when I restart the container but that it not the latest version.
```
$ sudo docker exec -it jotta /bin/bash
root@jotta:/src# apt list --upgradable
Listing... Done
root@jotta:/src# # apt-get update
[...]
Get:4 https://repo.jotta.us/debian debian InRelease [9417 B]
[...]
root@jotta:/src# apt list --upgradable
Listing... Done  
[...]
jotta-cli/debian 0.8.36055 amd64 [upgradable from: 0.7.33634]
[...]
root@jotta:/src# 
```
I am wondering if an "apt-get update" is needed in entrypoint.sh before "apt-get install jotta-cli" ?

**Comment by maaximal** [comment]
Thanks, good catch. Fixed it
